% Auto-generated by cameraCalibrator app on 08-Dec-2024
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\IZTARU\Desktop\Tefi\Robo\tarea7\IMG_20241208_231524024_HDR.jpg',...
    'C:\Users\IZTARU\Desktop\Tefi\Robo\tarea7\IMG_20241208_231528196_HDR.jpg',...
    'C:\Users\IZTARU\Desktop\Tefi\Robo\tarea7\IMG_20241208_231531742_HDR.jpg',...
    'C:\Users\IZTARU\Desktop\Tefi\Robo\tarea7\IMG_20241208_231549879_HDR.jpg',...
    'C:\Users\IZTARU\Desktop\Tefi\Robo\tarea7\IMG_20241208_231555320_HDR.jpg',...
    'C:\Users\IZTARU\Desktop\Tefi\Robo\tarea7\IMG_20241208_231615951_HDR.jpg',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 15;  % in units of 'centimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'centimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
showdemo('MeasuringPlanarObjectsExample')
showdemo('StructureFromMotionExample')
